# Generated by Django 4.0.1 on 2022-09-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_invoice_paid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_access',
            field=models.CharField(default='invoicing', max_length=255),
            preserve_default=False,
        ),
    ]
