# Generated by Django 4.0.1 on 2022-09-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icit', '0002_dummymachinetoken_icitmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icitmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
